// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBAjO9TrJ8gf-VTyyj9-lxuubmQ1cnkB8',
    appId: '1:391796268461:web:dbb481584d712e3ddbd524',
    messagingSenderId: '391796268461',
    projectId: 'cat-tarot',
    authDomain: 'cat-tarot.firebaseapp.com',
    storageBucket: 'cat-tarot.appspot.com',
    measurementId: 'G-8X4SH19882',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATuO41KER1wqu9Yq6vwccqRxbXlw8Di90',
    appId: '1:391796268461:android:af13e24ac6e53870dbd524',
    messagingSenderId: '391796268461',
    projectId: 'cat-tarot',
    storageBucket: 'cat-tarot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv-InE_EJmIKfrfL5E73Y7hdLkSz-bxPM',
    appId: '1:391796268461:ios:dd07405ddcfe76b0dbd524',
    messagingSenderId: '391796268461',
    projectId: 'cat-tarot',
    storageBucket: 'cat-tarot.appspot.com',
    iosClientId: '391796268461-1efj04802fcbf5hfmk6kvlsrria1pnn5.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv-InE_EJmIKfrfL5E73Y7hdLkSz-bxPM',
    appId: '1:391796268461:ios:dd07405ddcfe76b0dbd524',
    messagingSenderId: '391796268461',
    projectId: 'cat-tarot',
    storageBucket: 'cat-tarot.appspot.com',
    iosClientId: '391796268461-1efj04802fcbf5hfmk6kvlsrria1pnn5.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );
}
